name: UNIT TEST

on: 
  push:
    branches: 
      - main    

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: php-actions/composer@v6
      # - run: echo "Composer dependencies have been installed"
      # - run: vendor/bin/phpunit ./test
      - echo: Install Openfortivpn
      - run: sudo apt-get install -y openfortivpn

      - name: Connect to VPN
        run: |
          sudo openfortivpn --username=${{ secrets.VPN_USERNAME }} --password=${{ secrets.VPN_PASSWORD }} --trusted-cert=${{ secrets.VPN_CERT }} --host=${{ secrets.VPN_HOST }} --port=${{ secrets.VPN_PORT }}
