name: UNIT TEST

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      # - uses: php-actions/composer@v6
      - run: echo "Install Openfortivpn"
      - run: sudo apt-get install -y openfortivpn

      - name: Connect to VPN
        run: sudo openfortivpn ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --username=${{ secrets.VPN_USERNAME }} --password=${{ secrets.VPN_PASSWORD }} --trusted-cert=${{ secrets.VPN_CERT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Install XFREERDP"
      - run: sudo apt update
      - run: sudo apt install -y freerdp2-x11
      - run: echo "Connect to virtual server"
      - run: xfreerdp /u:${{ secrets.HOST_USER }} /p:${{ secrets.HOST_PASSWORD }} /v:${{ secrets.HOST}
      - name: Copy code to Windows Server
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.HOST_PASSWORD }}" scp -r ./path/to/files ${secrets.HOST_USER}@localhost:/c/Users/${{ secrets.HOST_USER }}/Deskto
      - name: Disconnect from VPN
        run: sudo killall openfortivpn
